### ISSUE TITLE
feat: Make WalletConnect decentralized.

### ISSUE THREAD

**Issue by drortirosh** [WalletConnect/blockchain-api#342]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

WalletConnect currently uses its proprietary servers to communicate between the wallet and the application.
This is a centralization vector that should be removed.

### Requested Behavior

WalletConnect should work without requirement of a dedicated servers.

WebRTC and its underlying technologies (stun/turn/ice) should suffice for most use cases.
Using WebRTC means the application can't rely on mobile "native" notifications, and has to keep an active connection with the server. On some platforms (e.g. iOS), it might require keeping the application "active".
I believe that in most cases this is a price users will agree to pay.

**Comment by arein** [comment]
We'll share our decentralization strategy which we've actively been working on for over a year soon. As you seem technically curious, here is a high-level overview: https://www.youtube.com/watch?v=wdvfl_Ku-xE

WebRTC is an idea we looked at for many reasons but not sure it addresses your motivation of decentralization.

**Comment by drortirosh** [comment]
First of all, I think we miss what "decentralized" mean. 
Few days ago, WalletConnect decided to block Ukraine from the network.
Even though this block was removed within hours, it still points that the network is centralized in that it can block users or country regions from the network.
(Let's ignore the fact that this block helps nothing: it only prevents non-techy guys from using their wallet devices, but doesn't affect techies or country-backed organizations)

By "decentralized" I mean how can a User with 2 endpoints (application and wallet) communicate with each other, without dependency on centralized servers.
