### ISSUE TITLE
feat: Adding Aurora rpc to providers

### ISSUE THREAD

**Issue by geekbrother** [WalletConnect/blockchain-api#463]
Adding [Aurora rpc](https://mainnet.aurora.dev/) to the providers.

**Comment by Solniechniy** [comment]
Hey, how it's going? I've just checking should we try to use custom jsonrpcprovider in our config or might be resolved today by your side?

**Comment by geekbrother** [comment]
> Hey, how it's going? I've just checking should we try to use custom jsonrpcprovider in our config or might be resolved today by your side?

Hey @Solniechniy! We are expecting it to be alive in our prod in 1-2 days.
