### ISSUE TITLE
feat: Add `Dexalot` and `Dexalot Testnet` RPC support

### ISSUE THREAD

**Issue by veyselozkahraman** [WalletConnect/blockchain-api#532]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Dexalot mainnet and subnets are on the Wallet Connect Chain List(https://docs.walletconnect.com/advanced/multichain/chain-list). However, these chains do not have RCP support. Dexalot application needs this functionality to support WalletConnect on the dApp(https://app.dexalot.com).

See https://github.com/WalletConnect/blockchain-api/blob/master/SUPPORTED_CHAINS.md

### Requested Behavior

Is it possible to add Dexalot mainnet and testnet?

```
Dexalot

Chain id: 432204
RPC: https://subnets.avax.network/dexalot/mainnet/rpc
```

```
Dexalot Testnet

Chain id: 432201
RPC: https://subnets.avax.network/dexalot/testnet/rpc
```

**Comment by chris13524** [comment]
> Dexalot application needs this functionality to support WalletConnect on the dApp

Dexalot application does not require rpc.walletconnect.com to support this chain in order to use WalletConnect. WalletConnect protocol is chain agnostic and supports all chains. rpc.walletconnect.com is our free blockchain RPC for a limited set of chains. If the chain is not supported, you/dapps may use an alternative RPC provider.

**Comment by veyselozkahraman** [comment]
> > Dexalot application needs this functionality to support WalletConnect on the dApp
> 
> Dexalot application does not require rpc.walletconnect.com to support this chain in order to use WalletConnect. WalletConnect protocol is chain agnostic and supports all chains. rpc.walletconnect.com is our free blockchain RPC for a limited set of chains. If the chain is not supported, you/dapps may use an alternative RPC provider.


This is the error I am getting when I try to sign a transaction on dexalot subnet.
```
Request URL: https://rpc.walletconnect.com/v1/?chainId=eip155:432201&projectId=<PROJECT_ID>
Request Method: POST
Status Code: 400 Bad Request

{
    "status": "FAILED",
    "reasons": [
        {
            "field": "chainId",
            "description": "We don't support the chainId you provided: eip155:432201. See the list of supported chains here: https://docs.walletconnect.com/cloud/blockchain-api#supported-chains"
        }
    ]
}

```

I do not get any errors if I want to sign a transaction on avalanche mainnet or testnet.
What seems to be the problem?

Thanks in advance

**Comment by veyselozkahraman** [comment]
I think the solution is to set the `rpcMap` option on initialization of the `EtheremProvider`

**Comment by chris13524** [comment]
> What seems to be the problem?

The Dexalot app shouldn't use rpc.walletconnect.com for any chains except for the ones in [supported chains](https://github.com/WalletConnect/blockchain-api/blob/master/SUPPORTED_CHAINS.md)

> I think the solution is to set the rpcMap option on initialization of the EtheremProvider

Yeah this is correct, you have to provide a custom rpc with `rpcMap` for unsupported chains.
