### ISSUE TITLE
feat: add Mantle chain support

### ISSUE THREAD

**Issue by wmzy** [WalletConnect/blockchain-api#537]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We are trying to use JSON Provider with Mantle, and the chain is not yet supported.

```json
{
    "status": "FAILED",
    "reasons": [
        {
            "field": "chainId",
            "description": "We don't support the chainId you provided: eip155:5000. See the list of supported chains here: https://docs.walletconnect.com/cloud/blockchain-api#supported-chains"
        }
    ]
}
```

### Requested Behavior

Please add support for Mantle:

Mantle Mainnet:

ChainID: 5000
HTTP Endpoint: https://rpc.mantle.xyz

Mantle Testnet(Goerli)
ChainID: 5001
HTTP Endpoint: https://rpc.testnet.mantle.xyz

Testnet (Sepolia):

ChainID: 5003
HTTP Endpoint: https://rpc.sepolia.mantle.xyz

**Comment by geekbrother** [comment]
We are currently considering options and demand for adding this network.
