### ISSUE TITLE
API to pull list of supported chains

### ISSUE THREAD

**Issue by chris13524** [WalletConnect/blockchain-api#566]
[Slack conversation](https://walletconnect.slack.com/archives/C04SYT4LU2W/p1709658823506369?thread_ts=1709319338.504139&cid=C04SYT4LU2W)

**Comment by geekbrother** [comment]
@chris13524 Do you know the use case on where this endpoint can be used?

**Comment by chris13524** [comment]
It would be used for Notify Server to know which chains are supported: https://github.com/WalletConnect/WalletConnectRust/pull/55#discussion_r1473594191

Also this: https://walletconnect.slack.com/archives/C03US3FRU9L/p1708706784442529?thread_ts=1701803594.483259&cid=C03US3FRU9L
