### ISSUE TITLE
Add Blast Support! 

### ISSUE THREAD

**Issue by duball69** [WalletConnect/blockchain-api#659]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I was trying to add Blast in my dapp, and with wallet connect it does not show up on the chain options. I believe it would be a simple feature to add, that could help a lot of devs! 

### Requested Behavior

The logo of Blast should appear and be added on the chain list.

I love WalletConnect btw!

**Comment by chris13524** [comment]
You can add support for any chains you like using the SDK configuration. This should be covered in [the docs](https://docs.walletconnect.com/web3modal/react/about)

**Comment by duball69** [comment]
Got you, will try it out. Thank you for the quick answer.
